<?php

return [
    'users' => ['read' => 'user_read', 'create' => 'user_create', 'update' => 'user_update', 'delete' => 'user_delete'],
    'roles' => ['read' => 'role_read', 'create' => 'role_create', 'update' => 'role_update', 'delete' => 'role_delete'],
    'language' => ['read' => 'language_read', 'create' => 'language_create', 'update' => 'language_update', 'update terms' => 'language_update_terms', 'delete' => 'language_delete'],
    'general settings' => ['read' => 'general_settings_read', 'update' => 'general_settings_update'],
    'storage settings' => ['read' => 'storage_settings_read', 'update' => 'storage_settings_update'],
    'recaptcha settings' => ['read' => 'recaptcha_settings_read', 'update' => 'recaptcha_settings_update'],
    'email settings' => ['read' => 'email_settings_read', 'update' => 'email_settings_update'],
    'categories' => ['read' => 'category_read', 'create' => 'category_create', 'update' => 'category_update', 'delete' => 'category_delete'],
    'property categories' => ['read' => 'property_category_read', 'create' => 'property_category_create', 'update' => 'property_category_update', 'delete' => 'property_category_delete'],
    'property facility types' => ['read' => 'property_facility_type_read', 'create' => 'property_facility_type_create', 'update' => 'property_facility_type_update', 'delete' => 'property_facility_type_delete'],
    'how-it-works' => ['read' => 'how-it-work_read', 'create' => 'how-it-work_create', 'update' => 'how-it-work_update', 'delete' => 'how-it-work_delete'],
    'testimonials' => ['read' => 'testimonial_read', 'create' => 'testimonial_create', 'update' => 'testimonial_update', 'delete' => 'testimonial_delete'],
    'blogs' => ['read' => 'blogs_read', 'update' => 'blogs_update', 'delete' => 'blogs_delete'],
    'blog categories' => ['read' => 'blog_categories_read', 'update' => 'blog_categories_update', 'delete' => 'blog_categories_delete'],
    'section title' => ['update' => 'section_titles'],
    'partners' => ['read' => 'partners_read', 'update' => 'partners_update', 'delete' => 'partners_delete'],
    'contacts' => ['read' => 'contact_read', 'delete' => 'contact_delete'],
    'about' => ['update' => 'about_update'],
    'Advertisement Permission' => ['update' => 'ad_action_permission'],
    'committee' => ['read' => 'committee_read', 'show' => 'committee_show', 'create' => 'committee_create', 'update' => 'committee_update', 'delete' => 'committee_delete'],
    'committee_member' => ['read' => 'committee_member_read', 'create' => 'committee_member_create', 'delete' => 'committee_member_delete'],
    'database_backup' => ['read' => 'db_backup_read', 'create' => 'db_backup_create', 'delete' => 'db_backup_delete'],
    'landlord' => ['read' => 'landlord_read', 'create' => 'landlord_create', 'update' => 'landlord_update', 'delete' => 'landlord_delete', 'show' => 'landlord_show'],
    'tenant' => ['read' => 'tenant_read', 'create' => 'tenant_create', 'update' => 'tenant_update', 'delete' => 'tenant_delete', 'show' => 'tenant_show', 'tenant_verify'],
    'rental' => ['read' => 'rental_read'],
    'reports' => ['tenant_report' => 'tenant_report', 'room_report' => 'room_report', 'payment_report' => 'payment_report'],
    'order' => ['read' => 'order_read', 'create' => 'order_create', 'update' => 'order_update', 'delete' => 'order_delete', 'show' => 'order_show', 'order_payment' => 'order_payment'],
    'account' => [
        'read' => 'account_read',
        'create' => 'account_create',
        'update' => 'account_update',
        'delete' => 'account_delete',
        'show' => 'account_show',
    ],
    'property' => [
        'read' => 'property_read',
        'create' => 'property_create',
        'update' => 'property_update',
        'delete' => 'property_delete',
        'show' => 'property_show',
    ],
    'property advertisement' => [
        'read' => 'property_advertisement_read',
        'create' => 'property_advertisement_create',
        'update' => 'property_advertisement_update',
        'delete' => 'property_advertisement_delete',
        'show' => 'property_advertisement_show',
    ],
    'account category' => [
        'read' => 'account_category_read',
        'create' => 'account_category_create',
        'update' => 'account_category_update',
        'delete' => 'account_category_delete',
        'show' => 'account_category_show',
    ],
    'payment' => [
        'read' => 'payment_read',
        'create' => 'payment_create',
        'update' => 'payment_update',
        'delete' => 'payment_delete',
        'show' => 'payment_show',
    ],
    'income' => [
        'read' => 'income_read',
        'create' => 'income_create',
        'update' => 'income_update',
        'delete' => 'income_delete',
        'show' => 'income_show',
    ],
    'expense' => [
        'read' => 'expense_read',
        'create' => 'expense_create',
        'update' => 'expense_update',
        'delete' => 'expense_delete',
        'show' => 'expense_show',
    ],
    'appointment' => [
        'read' => 'appointment_read',
        'create' => 'appointment_create',
        'update' => 'appointment_update',
        'delete' => 'appointment_delete',
        'show' => 'appointment_show',
    ],
    'timeslot' => [
        'read' => 'timeslot_read',
        'create' => 'timeslot_create',
        'update' => 'timeslot_update',
        'delete' => 'timeslot_delete',
        'show' => 'timeslot_show',
    ],
    'profile' => [
        'read' => 'profile_read',
        'update' => 'profile_update',
    ],
    'mailbox' => [
        'read' => 'mailbox_read',
        'create' => 'mailbox_create',
        'update' => 'mailbox_update',
        'delete' => 'mailbox_delete',
        'show' => 'mailbox_show',
    ],
    'smsbox' => [
        'read' => 'smsbox_read',
        'create' => 'smsbox_create',
        'update' => 'smsbox_update',
        'delete' => 'smsbox_delete',
        'show' => 'smsbox_show',
    ],
    'bill' => [
        'read' => 'bill_read',
        'create' => 'bill_create',
        'update' => 'bill_update',
        'delete' => 'bill_delete',
        'show' => 'bill_show',
    ],

];
